### ISSUE TITLE
Unable load to openalpr.dll library

### ISSUE THREAD

**Issue by TRSoft** [r1me/TOpenALPR#1]
delphi example error message "Unable load to openalpr.dll library" ......

**Comment by r1me** [comment]
Double check for prerequisite (Microsoft Visual C++ 2015 Redistributable) and follow instructions.

**Comment by Aurelisson** [comment]
Hi guys, I have the same problem: "Unable load to openalpr.dll library".
I'm using Delphi XE10 (10.2 Tokyo) on Windows 10, 32 bits with "Microsoft Visual C++ 2015 Redistributable" instalated (vc_redist.x86.exe).
Debbuging, I discover that: 
FLibOpenALPR := LoadLibrary(libopenalpr);  //Return "FLibOpenALPR = 0";

**Comment by ramosjairo** [comment]
I can't use the library. error message "Unable load to openalpr.dll library"
